### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by honestserpent** [Vincit/objection-find#18]
It looks like this project could be a very good addition to objection.js, and I am willing to try it and use it.

However, I am wondering whether it still is under development.

Is it still alive?

**Comment by igor-savin-ht** [comment]
Seeing that last committ was in October, and from third-party PR, I'd say that it is sorta-kinda alive, but not under very active development.

**Comment by kapouer** [comment]
This project is not under development. I'm not using it anymore.
I'm willing to somewhat continue to support it as far as i can, as a way to say thank you to @koskimas  for his work. So just SHOUT if you think something must be merged and i will LOOK at it.

Leaving this issue open so that anyone can see it first.

**Comment by igor-savin-ht** [comment]
@kapouer Any chance you could provide maintainer permissions to someone from community to make the project more future-proof in case you decide to eventually move on?

**Comment by kapouer** [comment]
Well i'm precisely in this situation right now. Anyone else can ask the project owner (not summoning him a second time) and i think he will gladly grant that.

**Comment by kibertoad** [comment]
@koskimas I've been thinking of rewriting test infrastructure of the project to something more modern and we intend to use this library heavily in our project; any chance I could be considered for a co-maintainer at some point? If there is any formal PR review process or something else that I would have to follow - I would be happy to comply.

**Comment by kapouer** [comment]
@kibertoad it would be easier if we could identify you as @igor-savin-ht...

**Comment by igor-savin-ht** [comment]
@kapouer "igor-savin-ht" is my corporate account; if I ever change place of employment, having project maintainership linked to it in GitHub would break things :).

**Comment by kapouer** [comment]
ok so you acknowledge kibertoad is your personal account ? (sorry but being explicit is a bit required here...)

**Comment by igor-savin-ht** [comment]
@kapouer Yes, kibertoad is my personal account.

**Comment by koskimas** [comment]
@kapouer I gave you admin rights for this repository. I give you full control over the future of this project.

I haven't personally contributed to this in ages, and I thought you would know better who could be the next maintainer(s).

**Comment by igor-savin-ht** [comment]
@kapouer Any updates :)?

**Comment by kapouer** [comment]
@kibertoad you have write access to the repository, and i'll give you publish access (if i can !) to the npm package in release+1 if you don't mind me being careful ;)

**Comment by igor-savin-ht** [comment]
@kapouer Awesome, thanks! What would be the best channel to reach out to you to discuss new features and refinements?

**Comment by kapouer** [comment]
here, in new issues ? or if really informal, by email is fine.

**Comment by kibertoad** [comment]
I presume we can close this issue now?..

**Comment by orditeck** [comment]
So, is this projet still under development? 😊

**Comment by kibertoad** [comment]
@orditeck Well, I am still committed to supporting it whenever needed and added some features our team missed, so sorta-kinda; I don't have a specific roadmap of things still missing, but if you have anything on your mind - please let me know, if it's reasonable, I'll do my very best to make it happen.

**Comment by orditeck** [comment]
Ok thanks, I just wanted to confirm whether the project was still maintained or not. This issue could be closed then IMO!

**Comment by DeanMauro** [comment]
@kibertoad Are you open to having another maintainer on the project? My team uses objection-find in production and we've been adding improvements in a fork up to this point, but would be happy to contribute for the community. 

Finished updates:
- Fixed aliasing of HasMany and ManyToMany relations (#81)
- Added support for filtering on multiple levels of relations (#91)

Future updates:
- Typescript support
- Configurable limits on nested relations (i.e. only allow filtering 3 levels deep)

**Comment by kibertoad** [comment]
@DeanMauro Considering that I don't have much time to dedicate to this project lately, would be grateful to get any help. Invite sent, and thank you!

**Comment by kibertoad** [comment]
@DeanMauro We probably should move from circleci to GitHub Actions and docker-compose based DB support, looks like CI was broken for a while.

**Comment by DeanMauro** [comment]
@kibertoad thank you!

Agreed on the ci. I'll take a peek. Let's see if we can get it back in working order through GA.
