### ISSUE TITLE
Isolate non-filtering data from filter parameter?

### ISSUE THREAD

**Issue by afm-sayem** [Vincit/objection-find#2]
Hi, great work on the library! I just found it while browsing your repo, I have looked at https://github.com/TryGhost/GQL earlier today for translating my find queries to knex runnable queries, but since I'm already using objectionjs this is the library I'm going to use. The library lacks discoverability a bit, so if you mentioned this in the official docs I think people like me would find it useful.

A few suggestions: 
- `eager` should not be part of the filter object, it should be a separate parameter. Since it's not technically being used to filter data.
- `orderBy` and `orderByDesc` should not be part of the filter object as well, candidate for a separate parameter. Also, I think orderByDesc could be implemented by including a negation character precede the value.
- `range` should be a separate parameter. Objection supports paging already, doesn't `page[size]` and `page[limit]` qualify as a better candidate?

I'm basing my suggestions off of [JSON API](http://jsonapi.org/examples/)

**Comment by afm-sayem** [comment]
The previous comment is in error. I haven't looked closely and it seems that there's no `filter` property. So  my suggestion would be to get all the filters in a single query parameter and then have separate parameters for `eager`, `orderBy` and `limit`

**Comment by afm-sayem** [comment]
Apologies for spamming. :cow: 

I just realized that whatever I mentioned can already be done since `findQuery` returns a queryBuilder instance. So effectively, I could put all the filters in a `filter` query parameter and use that to construct the find query. For `page` and the rest, I could define my own parameters and just call `page` method on the querybuilder instance.

**Comment by pthieu** [comment]
@afm-sayem: do you have an example of this?

**Comment by afm-sayem** [comment]
Here are some sample requests: https://github.com/afm-sayem/ground-zero/wiki/Sample-API-Requests

**Comment by pthieu** [comment]
@afm-sayem: sorry I meant in code, I took what you said about `findQuery` returning a `queryBuilder` instance, so I did this: 
```
const { limit = 1000 } = req.query || {};
const events = await findQuery(Model)
    .allowEager(`[${Object.keys(Model.relationMappings)}]`)
    .limit(limit)
    .build(req.query);
```

But I get this error:
```
StatusCodeError: 500 - {"success":false,"message":"findQuery(...).allowEager(...).limit is not a function"}
```

**Comment by pthieu** [comment]
@afm-sayem never mind, i just put it after the `.build`
