### ISSUE TITLE
please stop asking for my approvals :)

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection-find#34]
Though i'm usually pretty interested in what's happening here (and in objection.js which i'm watching thoroughly) please please directly commit now to the repository. If you do something wrong, users of the module will open issues.
Thank you !

**Comment by kapouer** [comment]
The message was meant for @kibertoad and community to find out he's the one in charge now.

**Comment by kibertoad** [comment]
@kapouer Thanks for the vote of confidence, will do!
