### ISSUE TITLE
can we search by timestamp ?

### ISSUE THREAD

**Issue by fatkhanfauzi** [Vincit/objection-find#40]
Hi,

i have a user that has createdAt value 2018-12-22 16:29:02.987406+00

I can't get any results with this query:
`createdAt:like = 2018-12-22
`

raised error:
`"message": "select \"users\".* from \"users\" where \"users\".\"created_at\" like $1 limit $2 - operator does not exist: timestamp with time zone ~~ unknown"
`

any idea? 
thanks.

**Comment by kibertoad** [comment]
@fatkhanfauzi Searching with like on timestamp sounds like a strange idea. Why not pass an interval instead?

**Comment by fatkhanfauzi** [comment]
@kibertoad hi. i ended up creating custom filter for this. thanks
