### ISSUE TITLE
Issue with filters: TypeError: this.relation.relatedTableAlias

### ISSUE THREAD

**Issue by vigzmv** [Vincit/objection-find#42]
Issue with filters

Only happens on usage with **objectionjs > 1.2.2** 

```js
module.exports = function(propertyRef, value, modelClass) {
   const fullColumnName = propertyRef.fullColumnName(),
  
  ...
}
```

on calling `propertyRef.fullColumnName()`
Error `TypeError: this.relation.relatedTableAlias is not a function` is thrown.

Any recommended solutions will be appreciated.
Thanks!

---

Update:
Looks like the `relatedTableAlias` was removed in https://github.com/Vincit/objection.js/compare/1.2.2...1.2.3#diff-1b101aaae4f893ec44a231f0578d57d7

**Comment by marcpearson** [comment]
I submitted a PR to fix the problem :)

**Comment by vigzmv** [comment]
Thankyou @marcpearson :tada:
