### ISSUE TITLE
any suggestions to sort by nested eager ?

### ISSUE THREAD

**Issue by fatkhanfauzi** [Vincit/objection-find#47]
hi,

currently it is not supported to sort by nested eager.
`Can only order by model's own properties and by BelongsToOneRelation relations' properties`/
OR
`PropertyRef: only one level of relations is supported`

i tried to make the relationships eager-able in one level but apparently it is not supported by objection js.
https://github.com/Vincit/objection.js/issues/1250

any suggestions to achieve that ? 

thanks in advance!

**Comment by mikevb3** [comment]
if i remember correctly you can sort by your fields.
Referencing #1250.

`await RequestOrder
  .query()
  .joinRelation('clusters.plans')`

`await RequestOrder
  .query()
  .joinRelation('clusters.plans')
.orderBy('clusters.plans.id', 'desc')
`

i havent tested it, but i remember i kinda did this, via that way.

**Comment by fatkhanfauzi** [comment]
> if i remember correctly you can sort by your fields.
> Referencing #1250.
> 
> `await RequestOrder .query() .joinRelation('clusters.plans')`
> 
> `await RequestOrder .query() .joinRelation('clusters.plans') .orderBy('clusters.plans.id', 'desc') `
> 
> i havent tested it, but i remember i kinda did this, via that way.


i was thinking if we can just do this in relationship method then we can always get sorted relationship.
but yeah.. i ended up doing manual query.
thanks
