### ISSUE TITLE
Objection 2 support

### ISSUE THREAD

**Issue by hassan-jahan** [Vincit/objection-find#59]
Hi,

Great job, Is there any plan to support objection 2?

**Comment by kibertoad** [comment]
There are! Didn't have time to work on it myself, unfortunately, help would definitely be appreciated

**Comment by marcpearson** [comment]
I already use objection 2 in my fork, a pull request was made and waiting to be merge. The required changes to be Objection 2 compatible are very small. I'll be glad to help but don't know what to do more then doing a pull request like i did

**Comment by hassan-jahan** [comment]
That's great. I'll check it out.

**Comment by kibertoad** [comment]
@marcpearson @hassan-jahan Fixed in 3.0.0!
