### ISSUE TITLE
Running Objection-find together with pagination?

### ISSUE THREAD

**Issue by IMilja** [Vincit/objection-find#68]
Hi there,
is there a method to use objection.js native *page* function together with objection-find to create pagination?

I tried to send a **page** and **limit** parameter in a *req.query* but since I tried to pass the full *req.query* object into the build function it tries to search for the page and limit properties.
One way I could do this is extract every property of the *req.query* and build a object for the build function but is there a better way?

**Comment by thisiskalnins** [comment]
@IMilja I don't know if it's still an issue for you and i don't know if this is the correct way, but i do this by destructing query parameter and adding it to build query.

```
const { page, ...query } = req.query;
const data = await findQuery(Model).build(query, Model.query().page(page, 12));
```

**Comment by IMilja** [comment]
@thisiskalnins it's never to late to learn something new :D... I kinda like this approach... I'm definitely going to use it in my future projects... Thank you!

**Comment by kibertoad** [comment]
@thisiskalnins Would you be open to submitting a documentation PR for this approach? I think it's a really cool, but completely undocumented feature.

**Comment by thisiskalnins** [comment]
@kibertoad Definitely! I'll try to do it this evening! :+1:
