### ISSUE TITLE
No way to search in postgres arrays ( array column not json or jsonb)

### ISSUE THREAD

**Issue by ahmadtofeeq** [Vincit/objection-find#69]
I have one region array in column. When i am trying to findquery and applying query into it. Searching inside array column doesn't work when array have more than one entry.

Case 1. array column(i.e. region)  is [NA-US] and search query is region={NA-US}. It works

Case 2. array column(i.e. region)  is [NA-US, AS-US] and search query is region={NA-US}. It doesn't works.

I tried with `ANY` operator in where clause by removing region from query. It gives error operator any is not permitted.

**Comment by kibertoad** [comment]
what SQL would work in this case?

**Comment by androidTrainner** [comment]
I haven't checked it with SQL. I think it's issue of objection-find not the database.

**Comment by kibertoad** [comment]
@androidTrainner I know. I just wonder if there is existing operator to map to that would produce the equivalent SQL.
Have you tried the `IN` operator?

**Comment by androidTrainner** [comment]
Yeah i have tried `IN`. Functionality of` IN` is different. IN doesn't work here as i need to search with in array as well as in all row. region data type is array.

**Comment by kibertoad** [comment]
Could be that we need a new operator then. If you provide a sample working SQL, I could add that.

**Comment by androidTrainner** [comment]
SELECT * FROM sal_emp WHERE 10000 = ANY (pay_by_quarter); [Will it help](https://www.postgresql.org/docs/9.1/arrays.html)?

**Comment by androidTrainner** [comment]
@kibertoad  I have created below filter to make it work for me
```
 // tslint:disable-next-line:no-any
const searchArray = (propertyRef: any, value: any) =>
    ({
        method: 'where',
        args: [propertyRef.fullColumnName(), '@>', value],
    });
```
Though i have few questions why operator `ANY` is not permitted in objection-find. However `@>` does provide the same output as `ANY`. Let me know if i need to raise a PR. Give me some direction how can we support `ANY` operator

**Comment by vigzmv** [comment]
@ahmadtofeeq We use the same solution, I think this should rather go into the Docs so anyone with custom requirements can create such filters.

**Comment by ahmadtofeeq** [comment]
@vigzmv  I second you on this. Hence workaround is there with custom filter, I am closing this issue.
