### ISSUE TITLE
Encounter findQuery(...).allowAll(...).allowGraph is not a function

### ISSUE THREAD

**Issue by tonypangs** [Vincit/objection-find#76]
Hi there, I am new to here and just encountered an issue when building a `findQuery`.
I was using `allowGraph()`to pass relations to withGraphFetched by following README.md
It returns `"message": "findQuery(...).allowAll(...).allowGraph is not a function"`
But after I moved `.build()` between `.allow()` and `.allowGraph()`, it works fine.
Is it my problem of understanding or there is something need to fix?

**After changes**
```js
    const JobsQuery = findQuery(Jobs)
      .allowAll()
      .build(req.query)
      .allowGraph(
        "[tags, job_category]"
      )
```

**Before Change**
```js
router.get("/jobs/search/", checkAuth, async (req, res, next) => {
  try {
    const user = req.user;
    const JobsQuery = findQuery(Jobs)
      .allowAll()
      .build(req.query)
      .allowGraph(
        "[tags, job_category]"
      );
    const result = await paginateQuery(JobsQuery, req, res, next);
    result.results = result.results.map(encapsulateJobFields);
    return res.status(200).json(result);
  } catch (error) {
    next(error);
  }
});
```

**Comment by thisiskalnins** [comment]
Hey, @tony1233465 

Your before and after code is the same.

I'm not 100% sure, but i think it's because _objection-find_ `FindQueryBuilder` doesn't have `.allowGraph()`, it has `.allowEager()`. When you put `.allowGraph()` after `.build()`, it inherits properties from _objection_'s `QueryBuilder`, which has `.allowGraph()` and that's why it works.

You probably need to write:
```js
const JobsQuery = findQuery(Jobs)
  .allowAll() // this is true by default, so no need to specify if left empty
  .allowEager('[tags, job_category]')
  .build(req.query);
```
Or if you specifically want to write `.allowGraph()`, you can write:
```js
const JobsQuery = findQuery(Jobs)
  .build(
    req.query,
    Jobs.query().allowGraph('[tags, job_category]')
  );
```

**Comment by tonypangs** [comment]
Sorry for the mistake.
thanks for your explanation, I will try again later

**Comment by thisiskalnins** [comment]
@tonypangs Did you manage to get this to work?

**Comment by tonypangs** [comment]
> @tonypangs Did you manage to get this to work?

At the end, I used `JobApplications.query().withGraphFetched("job.[district, job_category]");` in objection.js to solve this problem.
Thanks for your help!
