### ISSUE TITLE
Support for RelationThrough joins?

### ISSUE THREAD

**Issue by jamespb97** [Vincit/objection-find#78]
Hi, having trouble filtering our db with a through join relationship, I'm fairly new to objection so I could be missing something but can't seem to see anything if I am.
I have two models with a many to many relationship which is managed with a through relation on our Users model with a UserCompany model.

Users
````
class User extends Model implements IUser {
  static tableName = "users";
  id!: number;
  firstName!: string;

  companies?: Company[];

  static relationMappings = {
    companies: {
      relation: Model.ManyToManyRelation,
      modelClass: Company,
      join: {
        from: "users.id",
        through: {
          from: "user_companies.user_id",
          to: "user_companies.company_id",
        },
        to: "companies.id",
      },
    },
  };
}
````

Companies
````
class Company extends Model implements ICompany {
  static tableName = "companies";
  id!: number;
  name!: string;
}
````

UserCompany
````
class UserCompany extends Model {
  static tableName = "user_companies";
  id!: number;
  userId!: number;
  companyId!: number;
}
````

Performing a simple get users by company id lookup:
````
findQuery(User)
  .allow("id", "firstName", "companies.id")
  .allowEager("companies")
  .build({
    "companies.id:eq": "1",
  });
````

Expected result:
Should return list of users who belong to company with id of 1.

Results in following error message:
````
DBError: select `users`.* from `users` where exists (select 1 from `companies` as `Company` inner join `user_companies` on `Company`.`id` = `user_companies`.`company_id` where `user_companies`.`user_id` = `users`.`id` and `companies`.`id` = '1') limit 50 - SQLITE_ERROR: no such column: companies.id
````

The above sql script is invalid, it sets up the alias of `Companies` but on the final where clause it doesn't use the alias and instead uses the table name incorrectly. Correcting this error and running the script in my db works as expected.
Is there a way to remove this alias that it's creating or a way for it to actually apply the alias in the final where clause.

package.json
````
"objection": "^2.2.3",
"objection-find": "^3.0.1",
````

**Comment by thisiskalnins** [comment]
Hey.

Your query should include `join` with companies. It could look like
```
{
    join: 'companies',
    'companies.id': 1
}
```

**Comment by jamespb97** [comment]
@thisiskalnins Thanks! That seemed to have fixed that error and now returns everything as it should.

I would have thought the statements beforehand like `allow` and `allowEager` would build the query in such a way for me?

Here is the full query from my example if anyone else is interested:

````
findQuery(User)
  .allow("id", "firstName", "companies.id")
  .allowEager("companies")
  .build({
    join: "companies",
    "companies.id:eq": "1",
  });
````
